version: '3.8'

services:
  web:
    build: #.
      context: "https://github.com/COMS7900/HW.git#main:docker_my"  # git repo
    # container_name: my_web
    ports:
      - "8000:8080"  # port mapping
    volumes:
      - .:/app  # volume mapping
    restart: always  
